### ISSUE TITLE
Use a better approach to concurrent favicon lookups to the same origin

### ISSUE THREAD

**Issue by jfroelich** [jfroelich/rss-reader#455]
A feed frequently contains several entries pointing to articles on the same site. When polling visits each entry, it looks up the entries favicon. This leads to several lookups to the same origin.

I want to implement something that is opaque to polling, because I do not want polling to be concerned with it, so somewhere above or below the abstraction level of the favicon lookup function. 

This thing should somehow recognize that several requests are being made to the same origin. If a request is currently in-flight, then the new request should join that existing request as a waiter for its result instead of starting a new request.  If a request was recently completed, then a new lookup should recognize the request was recently performed and should use its result instead of performing a new request. If an existing request does not exist, then a new request should be registered so that other lookups that are to the same origin find it.

This is something like a queue. But I am not quite sure of the details, and am a bit fearful of the complexity.

**Comment by jfroelich** [comment]
This kind of this just showed up in the log:

```
HEAD https://www.lesserwrong.com/favicon.ico 404 ()
fetchWithTranslatedErrors @ utils.js:168
fetchWithTimeout @ utils.js:95
fetchImageHead @ fetch-image-head.js:33
FaviconLookup.fetchImage @ lookup.js:229
FaviconLookup.lookup @ lookup.js:198
async function (async)
FaviconLookup.lookup @ lookup.js:31
pollEntry @ poll-entry.js:99
async function (async)
pollEntry @ poll-entry.js:31
pollEntries @ poll-feed.js:168
pollFeed @ poll-feed.js:41
async function (async)
pollFeed @ poll-feed.js:13
pollFeeds @ poll-feeds.js:34
async function (async)
pollFeeds @ poll-feeds.js:21
checkForUpdatesButtonOnclick @ options-page.js:530
async function (async)
checkForUpdatesButtonOnclick @ options-page.js:513
lookup.js:235 FetchError: Response content type header not an image mime type text/plain; charset=utf-8 for url https://www.lesserwrong.com/favicon.ico
    at check (chrome-extension://inbglccifgaolbghcbchfpllijhkiolo/src/utils/check.js:21:17)
    at fetchImageHead (chrome-extension://inbglccifgaolbghcbchfpllijhkiolo/src/fetch/fetch-image-head.js:44:3)
    at <anonymous>
FaviconLookup.fetchImage @ lookup.js:235
async function (async)
FaviconLookup.fetchImage @ lookup.js:226
FaviconLookup.lookup @ lookup.js:198
async function (async)
FaviconLookup.lookup @ lookup.js:31
pollEntry @ poll-entry.js:99
async function (async)
pollEntry @ poll-entry.js:31
pollEntries @ poll-feed.js:168
pollFeed @ poll-feed.js:41
async function (async)
pollFeed @ poll-feed.js:13
pollFeeds @ poll-feeds.js:34
async function (async)
pollFeeds @ poll-feeds.js:21
checkForUpdatesButtonOnclick @ options-page.js:530
async function (async)
checkForUpdatesButtonOnclick @ options-page.js:513
utils.js:168 HEAD https://www.lesserwrong.com/favicon.ico 404 ()
fetchWithTranslatedErrors @ utils.js:168
fetchWithTimeout @ utils.js:95
fetchImageHead @ fetch-image-head.js:33
FaviconLookup.fetchImage @ lookup.js:229
FaviconLookup.lookup @ lookup.js:198
async function (async)
FaviconLookup.lookup @ lookup.js:31
pollEntry @ poll-entry.js:99
async function (async)
pollEntry @ poll-entry.js:31
pollEntries @ poll-feed.js:168
pollFeed @ poll-feed.js:41
async function (async)
pollFeed @ poll-feed.js:13
pollFeeds @ poll-feeds.js:34
async function (async)
pollFeeds @ poll-feeds.js:21
checkForUpdatesButtonOnclick @ options-page.js:530
async function (async)
checkForUpdatesButtonOnclick @ options-page.js:513
lookup.js:235 FetchError: Response content type header not an image mime type text/plain; charset=utf-8 for url https://www.lesserwrong.com/favicon.ico
    at check (chrome-extension://inbglccifgaolbghcbchfpllijhkiolo/src/utils/check.js:21:17)
    at fetchImageHead (chrome-extension://inbglccifgaolbghcbchfpllijhkiolo/src/fetch/fetch-image-head.js:44:3)
    at <anonymous>
FaviconLookup.fetchImage @ lookup.js:235
async function (async)
FaviconLookup.fetchImage @ lookup.js:226
FaviconLookup.lookup @ lookup.js:198
async function (async)
FaviconLookup.lookup @ lookup.js:31
pollEntry @ poll-entry.js:99
async function (async)
pollEntry @ poll-entry.js:31
pollEntries @ poll-feed.js:168
pollFeed @ poll-feed.js:41
async function (async)
pollFeed @ poll-feed.js:13
pollFeeds @ poll-feeds.js:34
async function (async)
pollFeeds @ poll-feeds.js:21
checkForUpdatesButtonOnclick @ options-page.js:530
async function (async)
checkForUpdatesButtonOnclick @ options-page.js:513
utils.js:168 HEAD https://www.lesserwrong.com/favicon.ico 404 ()
fetchWithTranslatedErrors @ utils.js:168
fetchWithTimeout @ utils.js:95
fetchImageHead @ fetch-image-head.js:33
FaviconLookup.fetchImage @ lookup.js:229
FaviconLookup.lookup @ lookup.js:198
async function (async)
FaviconLookup.lookup @ lookup.js:31
pollEntry @ poll-entry.js:99
async function (async)
pollEntry @ poll-entry.js:31
pollEntries @ poll-feed.js:168
pollFeed @ poll-feed.js:41
async function (async)
pollFeed @ poll-feed.js:13
pollFeeds @ poll-feeds.js:34
async function (async)
pollFeeds @ poll-feeds.js:21
checkForUpdatesButtonOnclick @ options-page.js:530
async function (async)
checkForUpdatesButtonOnclick @ options-page.js:513
lookup.js:235 FetchError: Response content type header not an image mime type text/plain; charset=utf-8 for url https://www.lesserwrong.com/favicon.ico
    at check (chrome-extension://inbglccifgaolbghcbchfpllijhkiolo/src/utils/check.js:21:17)
    at fetchImageHead (chrome-extension://inbglccifgaolbghcbchfpllijhkiolo/src/fetch/fetch-image-head.js:44:3)
    at <anonymous>
FaviconLookup.fetchImage @ lookup.js:235
async function (async)
FaviconLookup.fetchImage @ lookup.js:226
FaviconLookup.lookup @ lookup.js:198
async function (async)
FaviconLookup.lookup @ lookup.js:31
pollEntry @ poll-entry.js:99
async function (async)
pollEntry @ poll-entry.js:31
pollEntries @ poll-feed.js:168
pollFeed @ poll-feed.js:41
async function (async)
pollFeed @ poll-feed.js:13
pollFeeds @ poll-feeds.js:34
async function (async)
pollFeeds @ poll-feeds.js:21
checkForUpdatesButtonOnclick @ options-page.js:530
async function (async)
checkForUpdatesButtonOnclick @ options-page.js:513
utils.js:168 HEAD https://www.lesserwrong.com/favicon.ico 404 ()
fetchWithTranslatedErrors @ utils.js:168
fetchWithTimeout @ utils.js:95
fetchImageHead @ fetch-image-head.js:33
FaviconLookup.fetchImage @ lookup.js:229
FaviconLookup.lookup @ lookup.js:198
async function (async)
FaviconLookup.lookup @ lookup.js:31
pollEntry @ poll-entry.js:99
async function (async)
pollEntry @ poll-entry.js:31
pollEntries @ poll-feed.js:168
pollFeed @ poll-feed.js:41
async function (async)
pollFeed @ poll-feed.js:13
pollFeeds @ poll-feeds.js:34
async function (async)
pollFeeds @ poll-feeds.js:21
checkForUpdatesButtonOnclick @ options-page.js:530
async function (async)
checkForUpdatesButtonOnclick @ options-page.js:513
lookup.js:235 FetchError: Response content type header not an image mime type text/plain; charset=utf-8 for url https://www.lesserwrong.com/favicon.ico
    at check (chrome-extension://inbglccifgaolbghcbchfpllijhkiolo/src/utils/check.js:21:17)
    at fetchImageHead (chrome-extension://inbglccifgaolbghcbchfpllijhkiolo/src/fetch/fetch-image-head.js:44:3)
    at <anonymous>
FaviconLookup.fetchImage @ lookup.js:235
async function (async)
FaviconLookup.fetchImage @ lookup.js:226
FaviconLookup.lookup @ lookup.js:198
async function (async)
FaviconLookup.lookup @ lookup.js:31
pollEntry @ poll-entry.js:99
async function (async)
pollEntry @ poll-entry.js:31
pollEntries @ poll-feed.js:168
pollFeed @ poll-feed.js:41
async function (async)
pollFeed @ poll-feed.js:13
pollFeeds @ poll-feeds.js:34
async function (async)
pollFeeds @ poll-feeds.js:21
checkForUpdatesButtonOnclick @ options-page.js:530
async function (async)
checkForUpdatesButtonOnclick @ options-page.js:513
utils.js:168 HEAD https://www.lesserwrong.com/favicon.ico 404 ()
fetchWithTranslatedErrors @ utils.js:168
fetchWithTimeout @ utils.js:95
fetchImageHead @ fetch-image-head.js:33
FaviconLookup.fetchImage @ lookup.js:229
FaviconLookup.lookup @ lookup.js:198
async function (async)
FaviconLookup.lookup @ lookup.js:31
pollEntry @ poll-entry.js:99
async function (async)
pollEntry @ poll-entry.js:31
pollEntries @ poll-feed.js:168
pollFeed @ poll-feed.js:41
async function (async)
pollFeed @ poll-feed.js:13
pollFeeds @ poll-feeds.js:34
async function (async)
pollFeeds @ poll-feeds.js:21
checkForUpdatesButtonOnclick @ options-page.js:530
async function (async)
checkForUpdatesButtonOnclick @ options-page.js:513
lookup.js:235 FetchError: Response content type header not an image mime type text/plain; charset=utf-8 for url https://www.lesserwrong.com/favicon.ico
    at check (chrome-extension://inbglccifgaolbghcbchfpllijhkiolo/src/utils/check.js:21:17)
    at fetchImageHead (chrome-extension://inbglccifgaolbghcbchfpllijhkiolo/src/fetch/fetch-image-head.js:44:3)
    at <anonymous>
```
