### ISSUE TITLE
Bug in slideshow when navigating

### ISSUE THREAD

**Issue by jfroelich** [jfroelich/rss-reader#469]
moved from code, needs to be reformatted
// BUG: above, occured when pressing right arrow repeatedly, quickly. Once the bug occurs,
// navigation stops working (pressing right arrow no longer does anything)
// Note the error occured several times in a row for different entries (different ids)
// slideshow-page.js:170 InvalidStateError: entry 6616 already in read state
//    at check (chrome-extension://inbglccifgaolbghcbchfpllijhkiolo/src/utils/check.js:21:17)
//    at main (chrome-extension://inbglccifgaolbghcbchfpllijhkiolo/src/reader-db/entry-mark-read.js:35:3)
//    at <anonymous>
//slideshow-page.js:170 InvalidStateError: entry 6618 already in read state
//    at check (chrome-extension://inbglccifgaolbghcbchfpllijhkiolo/src/utils/check.js:21:17)
//    at main (chrome-extension://inbglccifgaolbghcbchfpllijhkiolo/src/reader-db/entry-mark-read.js:35:3)
//    at <anonymous>
// markSlideRead @ slideshow-page.js:170
//
// NOTE: I subscribed to a new feed in options page while slideshow was open, the new feed contains
// the same article that I had just read in the feed because I found the article interesting and
// decided to subscribe to the whole feed. That could be related
// Separately maybe it is wrong to treat this is an assertion error, maybe entryMarkRead should
// just become a no-op, and I should change the perspective of entryMarkRead into something like
// tryEnsureEntryMarkRead that explicitly becomes a no-op in the case of already being read, and
// just log the case of already being read as a warning to indicate something else is up, and not
// fail. Basically remove the guarantee that markSlideRead successfully affects the db.
// NOTE: in any case it should not cause the entire slideshow to stop working, that is also an
// error in some sense. Navigation should continue working. Whatever this error is, the whole UI
// should not break as a result. Maybe the catch block shouldn't return.

**Comment by jfroelich** [comment]
maybe slideshow needs to also react to entry-added event to check? entry added that resulted from subscribe. but entry should never have been added if it already existed? Seems incorrect.

**Comment by jfroelich** [comment]
The early exit was preventing additional slides being loaded in showNextSlide. Fixed by reverting to earlier approach, but only changing how the find next slide logic works.
